source 'https://github.com/CocoaPods/Specs.git'
ali_source 'alibaba-specs'
ali_source 'alibaba-specs-mirror'
platform :ios, '7.0'
#inhibit_all_warnings!

def common
	pod 'WeexSDK'
	pod 'WeexPluginLoader'#, '0.0.1.18'
    pod 'GCanvas', :git=>'git@gitlab.alibaba-inc.com:gcanvas/gcanvas.git', :branch=>'alibaba'
    pod 'SDWebImage', '3.7.5'
end

target 'WeexGcanvas' do
    common
end


