source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
#inhibit_all_warnings!

def common
	pod 'WeexSDK'
	pod 'GCanvas'
	pod 'SDWebImage', '3.7.5'
	pod 'WeexPlugin', :git => 'https://github.com/kfeagle/WeexPlugin.git'
end

target 'WeexGCanvas' do
    common
end


